[package]
name = "hmdee"
version = "0.1.0"
authors = ["Dylan McKay <me@dylanmckay.io>"]
edition = "2018"

[features]
default = ["psvr"]

[dependencies]
hmdee_core = { path = "../core", version = "0.1.0" }
hidapi = "1.2"
psvr = { path = "../psvr", optional = true }

