[package]
name = "hmdee"
version = "0.1.0"
authors = ["Dylan McKay <me@dylanmckay.io>"]

[features]
default = ["psvr"]

[dependencies]
hmdee_core = { path = "../core", version = "0.1.0" }
psvr = { path = "../psvr", optional = true }

